services:
  jupyter:
    build:
      context: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    working_dir: /home/jovyan/work
    command: start-notebook.py --NotebookApp.token='my-token'

volumes:
  jupyter-data:
    name: jupyter-data

